image: mcr.microsoft.com/playwright:v1.54.2-noble

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

stages:
  - install
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  APP_BASE_URL: "http://localhost:3000"
  API_BASE_URL: "http://localhost:3000"

cache:
  - key: "test-deps-$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/
      - node_modules/
    policy: pull-push
  - key: "app-$CI_COMMIT_REF_SLUG"
    paths:
      - /tmp/juice-shop/node_modules/
    policy: pull-push

install_dependencies:
  stage: install
  script:
    - echo "Start preparing app for testing..."
    - git clone https://github.com/niks-xz/my-juice-shop.git /tmp/juice-shop
    - cd /tmp/juice-shop
    - npm install
    - npm run start &
    - echo "Installing dependencies for testing..."
    - cd $CI_PROJECT_DIR
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

run_tests:
  stage: test
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - allure-results/
      - test-results/
      - playwright-report/
    expire_in: 1 hour
  dependencies:
    - install_dependencies
