name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  setup_project:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble

    steps:
    - uses: actions/checkout@v4

    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: node_modules
        path: node_modules
        retention-days: 1

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    needs: setup_project

    steps:
    - uses: actions/checkout@v4

    - name: Download node_modules
      uses: actions/download-artifact@v4
      with:
        name: node_modules
        path: node_modules

    - name: Run tests
      run: npm run test

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          allure-results/
          test-results/
          playwright-report/
        retention-days: 1
